name: Telegram Streamer

on:
  workflow_dispatch: # تشغيل يدوي

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 350 # لضمان استمرار البث لأطول فترة ممكنة

    steps:
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Start Streaming
        run: |
          while true; do
            ffmpeg -re -i "http://g.betlxz.xyz/st/sh/203885?token=ShN0YQ0JGlhBVEk9ShAWG04kBi5fWQJEC0E8WgsHJDJHQQQJQQQQQ1JHG0EQQQQQQQ0QQQ0UWwVQAVVQUwxNQ0QQQQQQQQxAWUcQAQQQQQQQRhVGQQQQQUcNUFJQDFFQBQQACEgSQQQQRw1BQQQHQQQQQEYcFAQQQQQQQQQQQQQQQQQQQRICDBYJW09EV1xnBQFUBV5SQw5HBkNJRAQQQRMLXEQIXB.RAAQxDEQdMVxpbRghcBwBDGEdUDhAITRMYEwsQdSESFEAGHUMGCEtbVw9GA0ZERUMYR14SOhRcEhVDVFNcAUIaWEFVFU9EVVNAPgdWCl5TAkAMQQQQRANDQBMdEFQQQQQQAQQQEQQQEAJDQQQQQQQQQ0dK" \
            -c:v libx264 -preset veryfast -b:v 3000k -maxrate 3000k -bufsize 6000k \
            -pix_fmt yuv420p -g 60 -keyint_min 60 -sc_threshold 0 \
            -vf "scale=1280:-2,fps=30" \
            -c:a aac -b:a 128k -ar 44100 \
            -f flv "rtmps://dc4-1.rtmp.t.me/s/2198320393:G-qUG1bneFtCdgCLNd1eFA" || echo "حدث انقطاع، إعادة المحاولة..."
            sleep 5
          done
