name: Kick Streamer FinalOK

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Start Streaming
        run: |
          while true; do
            ffmpeg -re -i "http://tv.vibertv.online:2052/live/shaqlawatv/starz1/stream.m3u8" \
            -c:v libx264 -preset ultrafast -tune zerolatency \
            -b:v 2500k -maxrate 2500k -bufsize 5000k \
            -vf "scale=1280:720,format=yuv420p" -g 50 \
            -c:a aac -b:a 128k -ar 44100 \
            -f flv "rtmp://fa723fc1b171.global-contribute.live-video.net/app/Sk_us-west-2_YL5q2zli0shi_oUP1cjd3cHf4RMojJotSOewU0KK6QJ" || echo "Error occurred, retrying..."
            sleep 5
          done
